import {Link} from "@/src/components/SiteLink";
import {Building2,Landmark,Calculator,Scale,BriefcaseBusiness,Truck,Check,ArrowRight} from "lucide-react";
import {categoryMeta,byCategory,type CategoryKey} from "@/src/content/services";
import {CtaBand} from "@/src/components/CtaBand";
import {ScrollableServices} from "@/src/components/ScrollableServices";
import {HomeHero} from "@/src/components/HomeHero";
const cats:CategoryKey[]=["business-setup","visas","tax-accounting","corporate-legal","business-support","logistics-concierge"];
const icons=[Building2,Landmark,Calculator,Scale,BriefcaseBusiness,Truck];
const reasons=[
 ["01","One point of contact","Coordinate connected business and personal requirements through one service relationship."],
 ["02","A clear process","Understand likely steps, documents and professional handoffs before work progresses."],
 ["03","Business + personal","Move from company setup to residency, family, payroll, tax and logistics without starting over."],
 ["04","Cautious professional scope","Regulated legal, audit and valuation work is coordinated with qualified providers where required."],
 ["05","Ongoing support","Continue after formation with recurring accounting, tax, employee and administrative services."],
];
const faqs=[
 ["Can foreign investors establish a UAE company?","Foreign investors can establish businesses through many UAE mainland and free-zone structures. The suitable route depends on activity, location, ownership, office and visa requirements."],
 ["Should I choose mainland or a free zone?","There is no universal best option. Customer market, activity, premises, visa needs and future expansion should be compared before selecting a jurisdiction."],
 ["Can you support visas after company formation?","Yes. Connected support can include investor, partner and employee residency plus eligible family sponsorship applications."],
 ["Can you guarantee a Golden Visa or bank account?","No. Authority and bank decisions are independent. Hexa Beam can assess readiness, coordinate documentation and support the process without making approval guarantees."],
 ["Do you provide ongoing accounting and payroll?","Yes. Bookkeeping, accounting, VAT, Corporate Tax, payroll and WPS support can continue as an ongoing engagement."],
];
export default function Home(){const schema={"@context":"https://schema.org","@type":"Organization",name:"Hexa Beam",url:"https://hexabeam.ae",areaServed:"United Arab Emirates",description:"Coordinated UAE business, residency, tax, accounting, corporate support, logistics and concierge services."};return <main id="main">
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
 <HomeHero/>
 <div className="trust-strip"><div className="container">{cats.map((c,i)=>{const Icon=icons[i];return <Link className="trust-item" href={`/${c}/`} key={c}><Icon size={17}/>{categoryMeta[c].name}</Link>})}</div></div>
 <section className="section intro-story"><div className="container grid-2"><div><h2 style={{margin:"0 0 24px"}}>One plan for your next move in Dubai and the UAE.</h2><p className="lead">Company setup can lead to residency, banking, accounting, tax, payroll and family requirements. We connect those steps so you can move from an initial decision to day-to-day life and business in the UAE with greater clarity.</p></div><div className="intro-visual"><figure className="editorial-collage"><img src="/assets/brand/hexabeam-general-collage.png" alt="Hexa Beam Dubai and UAE business, legal, residency and logistics services"/><figcaption>One coordinated Dubai and UAE service ecosystem</figcaption></figure><div className="intro-diagram"><div><b>01: Establish</b><p>Structure, activity, licence and corporate records.</p></div><div><b>02: Reside</b><p>Investor, employee and family residency pathways.</p></div><div><b>03: Operate</b><p>Banking readiness, books, tax, payroll and WPS.</p></div><div><b>04: Protect and grow</b><p>Documentation, succession, compliance and support.</p></div></div></div></div></section>
 <section className="section muted-bg" id="services"><div className="container"><div className="section-head"><div><div className="eyebrow">Dubai and UAE services</div><h2>Services organised around what you need to achieve.</h2></div><div className="section-head-action"><p className="lead">Start with company setup, residency, tax, legal support or logistics, then connect the related requirements in one clear plan.</p><Link className="btn btn-dark" href="/services/">Explore all services <ArrowRight size={16}/></Link></div></div><div className="category-grid">{cats.map((cat,i)=>{const Icon=icons[i];return <article className="category-card" key={cat}><Icon size={29}/><h3>{categoryMeta[cat].name}</h3><p>{categoryMeta[cat].description}</p><div className="service-links">{byCategory(cat).slice(0,4).map(s=><Link key={s.slug} href={`/services/${s.slug}/`}>{s.name}</Link>)}</div></article>})}</div></div></section>
 <ScrollableServices/>
 <section className="feature feature-portal"><div className="feature-portal-bg" aria-hidden="true"/><img className="feature-portal-frame" src="/assets/brand/start-uae-golden-frame.png" alt="" aria-hidden="true"/><img className="feature-portal-frame feature-portal-frame-front" src="/assets/brand/start-uae-golden-frame.png" alt="" aria-hidden="true"/><div className="container feature-portal-content"><div className="eyebrow">Company setup in Dubai and the UAE</div><h2>Choose a company structure that fits how you will operate.</h2><p>Compare Dubai mainland, UAE free-zone and offshore options by activity, ownership, visas, premises and ongoing obligations.</p><div className="points">{["Jurisdiction comparison","Licence coordination","Corporate documents","Residency planning","Banking readiness","Accounting handover"].map(x=><div className="point" key={x}><Check size={16} color="var(--gold-400)"/>{x}</div>)}</div><Link href="/services/company-formation/" className="btn btn-primary">Explore company formation <ArrowRight size={16}/></Link></div></section>
 <section className="section"><div className="container why-grid"><div><div className="eyebrow">Why Hexa Beam</div><h2 style={{marginTop:16}}>A clearer way to navigate Dubai and the UAE.</h2><p className="lead" style={{marginTop:20}}>Understand what comes next, which requirements connect and who is responsible for each step.</p></div><div className="why-list">{reasons.map(r=><div className="why-item" key={r[0]}><span>{r[0]}</span><div><h3>{r[1]}</h3><p>{r[2]}</p></div></div>)}</div></div></section>
 <section className="section navy-bg"><div className="container"><div className="section-head"><div><div className="eyebrow">How it works</div><h2>From a Dubai or UAE requirement to a clear next step.</h2></div><p className="lead">A practical five-step process keeps documents, applications and professional handoffs visible from the start.</p></div><div className="steps">{[["01","Tell us your objective","Share what you need, your current position and timing."],["02","Receive a clear plan","We map the steps, documents and connected services."],["03","Prepare the file","Documents are reviewed before the process moves forward."],["04","We coordinate","Applications, appointments and approved handoffs are tracked."],["05","Know what comes next","Receive the completed records and next-step guidance."]].map(s=><div className="step" key={s[0]}><b>STEP {s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div><div className="how-works-cta"><div><span>Ready to begin?</span><p>Tell us what you want to achieve in Dubai or the UAE and we will map the clearest route forward.</p></div><Link className="btn btn-primary" href="/contact/">Plan your next step <ArrowRight size={16}/></Link></div></div></section>
 <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">Ongoing UAE business support</div><h2>Keep your business moving after setup.</h2></div><p className="lead">Manage renewals, employees, accounting, tax, payroll, corporate records and government procedures as the business grows.</p></div><div className="category-list">{["licence-renewal-amendments","bookkeeping-accounting","corporate-tax","wps-salary-transfers","corporate-documentation","pro-government-services"].map(slug=>{const s=cats.flatMap(byCategory).find(x=>x.slug===slug)!;return <article className="service-tile" key={slug}><h3>{s.name}</h3><p>{s.heroDescription}</p><Link href={`/services/${slug}/`}>View service</Link></article>})}</div></div></section>
 <section className="section muted-bg"><div className="container"><div className="section-head"><div><div className="eyebrow">Dubai and UAE questions</div><h2>Clear answers before you take the next step.</h2></div></div><div className="faq">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section>
 <CtaBand/>
 </main>}
