export type CategoryKey = "business-setup" | "visas" | "accounting" | "tax-accounting" | "corporate-legal" | "corporate-services" | "property-valuation" | "logistics" | "chauffeur-transport";

export type Service = {
  slug:string; name:string; navLabel:string; category:CategoryKey; heroTitle:string; heroDescription:string;
  intro:string; audiences:string[]; assistance:string[]; process:string[]; considerations:string[];
  faq:{q:string;a:string}[]; cta:string; regulated?:string;
};

const commonProcess = ["Discuss the requirement and intended outcome", "Review eligibility, structure and likely document requirements", "Prepare and check the application file", "Coordinate submissions, appointments or third-party steps", "Provide completion updates and explain any follow-on requirements"];
const commonFaq = (name:string,assistance:string[]) => [
  {q:`What can Hexa Beam coordinate for ${name}?`,a:`Depending on the case, support can include ${assistance.slice(0,3).join(", ")}. The exact scope, responsibilities and exclusions are confirmed in writing before work begins.`},
  {q:`What can affect the timing for ${name}?`,a:"Timing depends on the current status, document readiness, authority or provider requirements and any external approvals involved. The likely sequence is explained after the initial review."},
];

type Seed = [string,string,CategoryKey,string,string[],string[],string?,string?];
const seeds:Seed[] = [
 ["company-formation","Company Formation","business-setup","Structure and establish your UAE company with a clear plan for licensing, ownership, visas and ongoing obligations.",["Entrepreneurs entering the UAE","Foreign investors","Existing businesses expanding into the UAE","Founders comparing mainland, free zone and offshore options"],["Business activity and jurisdiction comparison","Trade-name and initial-approval coordination","Corporate document preparation","Establishment and residency coordination","Office and address requirement support","Post-formation compliance handover"]],
 ["mainland-company-setup","Mainland Company Setup","business-setup","Prepare a UAE mainland company setup around your activity, operating model and market requirements.",["Businesses serving the local UAE market","Companies requiring flexible commercial operations","Professional and commercial activity founders"],["Activity and legal-form review","Trade-name reservation","Initial and external approvals coordination","Licence file preparation","Office requirement guidance","Partner and employee residency support"]],
 ["free-zone-company-setup","Free Zone Company Setup","business-setup","Compare free-zone options by activity, facility, visa allocation and operating needs, not headline price alone.",["International founders","Export and services businesses","Remote and regional teams"],["Free-zone comparison","Licence and activity selection","Incorporation document preparation","Facility and visa planning","Establishment card coordination","Renewal planning"]],
 ["offshore-company-setup","Offshore Company Setup","business-setup","Coordinate an offshore structure only where it fits the intended ownership, holding or international activity.",["International investors","Holding and asset-structuring clients","Cross-border businesses requiring professional advice"],["Purpose and suitability review","Registered-agent coordination","KYC file preparation","Corporate documentation","Banking-readiness support","Ongoing compliance coordination"],undefined,"Offshore structures may involve legal and tax consequences in more than one jurisdiction. Independent professional advice may be required."],
 ["trade-licence-support","Trade Licence Support","business-setup","Move from an intended business activity to the appropriate UAE licence and approval path.",["New founders","Existing companies adding activities","Businesses changing jurisdiction or operating model"],["Activity classification review","Trade-name and initial approval","External approval coordination","Licence application documentation","Issuance follow-up","Compliance handover"]],
 ["licence-renewal-amendments","Licence Renewal & Amendments","business-setup","Keep corporate records aligned when renewing a licence or changing activities, owners, managers or addresses.",["Active UAE companies","Businesses restructuring operations","Companies approaching licence expiry"],["Licence renewal","Activity amendments","Shareholder and manager changes","Trade-name changes","Address amendments","Corporate record updates"]],
 ["company-liquidation","Company Liquidation","business-setup","Close a UAE entity through an orderly plan covering licences, employees, clearances and final records.",["Dormant companies","Owners exiting the UAE","Businesses completing a restructuring"],["Liquidation pathway review","Licence and establishment-card cancellation","Visa cancellation coordination","Government clearance support","Liquidator coordination where required","Final deregistration documentation"],undefined,"Where a liquidator, auditor or legal professional is required, Hexa Beam coordinates with appropriately qualified third parties."],
 ["investor-partner-visa","Investor / Partner Visa","visas","Coordinate residency steps connected with eligible ownership or partnership in a UAE company.",["Company shareholders","Business partners","Founders establishing UAE residency"],["Eligibility and company-document review","Entry permit or status coordination","Medical and Emirates ID steps","Residency application support","Renewal and cancellation planning"]],
 ["employee-visa","Employee Visa","visas","Support employers through employee immigration, identity and residency administration.",["UAE employers","Newly formed companies","Businesses expanding their teams"],["Employment entry-permit coordination","Labour-related application support","Medical fitness arrangements","Emirates ID coordination","Residency processing","Renewal, status change and cancellation"]],
 ["family-visa","Family Visa","visas","Coordinate dependent residency documentation for eligible UAE sponsors and their immediate families.",["UAE residents sponsoring spouses","Parents sponsoring eligible children","Eligible residents exploring parent sponsorship"],["Sponsor eligibility review","Entry-permit coordination","Document relationship review","Medical and Emirates ID steps","Status change support","Renewal and cancellation"]],
 ["golden-visa","Golden Visa","visas","Assess the relevant long-term residency category and coordinate a properly documented application.",["Qualifying investors and property owners","Entrepreneurs","Specialised professionals","Other applicants within published eligibility categories"],["Initial category assessment","Evidence and document checklist","Nomination or application coordination where applicable","Medical and Emirates ID steps","Eligible family application coordination","Renewal support"],"Golden Visa eligibility and final approval depend on the applicant’s category and current requirements of the relevant UAE authorities."],
 ["visa-renewal","Visa Renewal","visas","Plan residency renewal before expiry and identify connected identity, medical or sponsor-document requirements.",["Employees","Investors and partners","Eligible dependants"],["Expiry and status review","Sponsor-document checks","Medical and identity coordination","Renewal submission support","Completion tracking"]],
 ["visa-cancellation","Visa Cancellation","visas","Coordinate visa cancellation and related status steps when employment, sponsorship or UAE plans change.",["Departing employees","Changing sponsors","Companies closing or restructuring"],["Status and sponsor review","Cancellation document preparation","Authority submission coordination","Dependent-status considerations","Follow-on status guidance"]],
 ["bookkeeping-accounting","Bookkeeping & Accounting","accounting","Build reliable monthly records that support decisions, reporting and UAE compliance work.",["SMEs","Newly established businesses","Growing companies improving finance processes"],["Monthly bookkeeping","General ledger maintenance","Payables and receivables","Bank reconciliation","Management reporting","Financial statement preparation","Payroll and tax-record support"]],
 ["vat","VAT Support","tax-accounting","Coordinate VAT registration, records and return preparation around the business’s actual transactions.",["VAT-registered businesses","Businesses approaching registration considerations","Companies correcting accounting records"],["Registration and deregistration assistance","Return preparation support","Input and output VAT reconciliation","Record review","Filing coordination","Compliance issue triage"],undefined,"Tax agent representation, where needed, must be delivered by an appropriately registered professional."],
 ["corporate-tax","Corporate Tax Support","tax-accounting","Prepare registrations, financial records and return inputs for the UAE Corporate Tax framework.",["UAE companies","Free-zone entities","Groups and branches requiring case-specific review"],["Registration and deregistration support","Accounting-readiness review","Taxable-income calculation support","Return preparation and filing coordination","Record and election tracking","Tax residency documentation support"],undefined,"Tax treatment depends on the entity, transactions and applicable law. Specialist tax advice may be required."],
 ["payroll-management","Payroll Management","tax-accounting","Run a clearer monthly payroll process with salary records, calculations and reporting.",["SMEs","Employers scaling teams","Businesses formalising payroll controls"],["Salary and allowance calculations","Deduction calculations","Payroll records and payslips","Monthly payroll reports","WPS preparation","Salary-transfer coordination"]],
 ["wps-salary-transfers","WPS & Salary Transfers","tax-accounting","Coordinate payroll files and salary-transfer administration for employers subject to WPS requirements.",["UAE employers","SMEs needing recurring payroll support","Companies correcting salary-file workflows"],["WPS setup assistance","Salary file preparation","Transfer coordination","Employee salary records","Monthly reports","Payment tracking"]],
 ["audit-assistance","Audit Assistance","tax-accounting","Prepare records and coordinate with a qualified auditor where an audit is required.",["Companies with statutory audit requirements","Businesses seeking management assurance","Entities preparing for renewal or stakeholder review"],["Audit-readiness review","Financial statement preparation","Supporting-document organisation","Auditor coordination","Query management","Reconciliation support"],undefined,"Hexa Beam provides preparation and coordination; regulated audit opinions are issued only by qualified auditors."],
 ["power-of-attorney","Power of Attorney","corporate-legal","Coordinate the right Power of Attorney document, translation, notarisation and attestation pathway for the intended use.",["Individuals managing property or personal affairs","Shareholders and company managers","Clients appointing representatives"],["General and special POA coordination","Property and company POA support","Vehicle and banking-related documentation","Drafting coordination with legal professionals where required","Notarisation and attestation coordination","Revocation support"]],
 ["inheritance-estate-legal-heir","Inheritance, Estate & Legal Heir Assistance","corporate-legal","Navigate the administrative side of an estate with careful coordination across documents, assets and qualified professionals.",["Families handling a UAE estate","Heirs with property, bank or company interests","Executors and representatives coordinating UAE assets"],["Estate-file and succession-document coordination","Death certificate and heir-document review","Property and share-transfer administration","Bank and asset documentation coordination","Court, notary and professional appointment coordination","Legal translation and attestation arrangements"],"Hexa Beam does not claim to provide court representation. Legal advice and representation are handled by appropriately qualified professionals where required."],
 ["succession-planning","Succession Planning","corporate-legal","Plan before an event occurs: ownership continuity, document readiness and the transfer of business or family assets.",["Business owners","Property investors","Families with UAE assets","Shareholders planning continuity"],["Succession requirements mapping","Will registration coordination","Ownership and share-transfer planning support","POA and corporate document coordination","Professional legal and tax referrals","Document inventory preparation"],undefined,"Succession outcomes are fact-specific. Independent legal and tax advice should be obtained for substantive planning decisions."],
 ["document-attestation","Document Attestation","corporate-legal","Coordinate authentication steps for personal, educational and corporate documents used in or outside the UAE.",["Employees and residents","Families","Companies using foreign-issued documents"],["Document-pathway review","Educational, marriage and birth certificate support","Corporate and commercial document coordination","Embassy and MOFA-related coordination","Collection and delivery planning"]],
 ["legal-translation","Legal Translation","corporate-legal","Coordinate certified translation of documents required for UAE applications and proceedings.",["Individuals with foreign-language records","Companies submitting corporate documents","Clients preparing notarisation or court files"],["Source-document review","Language-pair coordination","Certified translation through appropriate providers","Format and name consistency checks","Attestation handoff where required"],undefined,"Certified or legal translation is delivered through appropriately authorised translation providers."],
 ["aml-ubo-compliance","AML & UBO Compliance","corporate-legal","Organise ownership and compliance records around applicable UAE obligations and the business’s risk profile.",["UAE companies maintaining ownership records","Businesses within regulated sectors","Groups with layered ownership"],["UBO information gathering","Declaration support","CDD record templates","Compliance policy coordination","Record-keeping review","Specialist referral where necessary"]],
 ["corporate-bank-account","Corporate Bank Account Assistance","corporate-services","Prepare a clear, complete banking application while recognising that account approval belongs to the bank.",["New UAE companies","Existing businesses changing banking relationships","International founders preparing UAE KYC"],["Bank-option orientation","KYC document preparation","Business profile and activity narrative","Source-of-funds document guidance","Meeting coordination","Application follow-up"],undefined,"Bank account approval, onboarding requirements and timing remain entirely at the bank’s discretion."],
 ["property-valuation","Property Valuation Support","property-valuation","Coordinate a professional valuation for a property, financing, investment or residency-related requirement.",["Property owners and investors","Companies valuing assets","Clients preparing finance or Golden Visa documentation"],["Requirement and property-document review","Approved valuation provider coordination","Residential and commercial valuation support","Inspection scheduling","Report handover and related-document coordination"],"Formal valuation reports are issued by appropriately approved valuation providers."],
 ["pro-government-services","PRO & Government Services","corporate-services","Coordinate recurring licence, immigration, labour and administrative submissions for UAE businesses.",["SMEs without an internal PRO team","Growing employers","Companies with recurring government administration"],["Government application coordination","Establishment and immigration documentation","Labour-related administration","Licence modifications","Document collection and submission","Status follow-up"]],
 ["trademark-assistance","Trademark Assistance","corporate-services","Coordinate the administrative path for UAE trademark search, classification, filing and renewal.",["New brands","Existing UAE companies","International businesses entering the market"],["Search and availability coordination","Class selection support","Application preparation","Submission coordination","Status tracking","Renewal administration"],undefined,"Legal opinions and contentious trademark matters are referred to appropriately qualified professionals."],
 ["business-relocation","Business Relocation","corporate-services","Bring company, residency, family, banking and operational setup into one coordinated UAE relocation plan.",["Founders relocating to the UAE","International companies moving teams","Families combining business and residency needs"],["Company formation","Investor and family residency coordination","Banking-readiness support","Accounting and tax setup","Office and property support","Airport and transport coordination"]],
 ["business-payment-solutions","Business Payment Solutions","corporate-services","Prepare introductions and application files for merchant, gateway, POS and cross-border payment providers.",["Retail and ecommerce businesses","Professional services firms","Companies improving collections"],["Requirement review","Provider introductions","KYC preparation","Merchant and gateway application support","POS coordination","Follow-up with providers"],undefined,"Availability, pricing and approval remain subject to the chosen regulated provider."],
 ["freight-logistics","Freight & Logistics","logistics","Coordinate commercial shipments across air, sea and road routes with clear documentation and handoffs.",["Importers and exporters","Trading companies","Businesses requiring local or international freight"],["Air, sea and road freight coordination","Import and export documentation","Customs clearance coordination","Cargo handling","Door-to-door delivery","Warehousing coordination"]],
 ["limousine-chauffeur","Limousine & Chauffeur Service","chauffeur-transport","Arrange professional UAE ground transportation for executives, families, events and VIP guests.",["Business travellers","Corporate teams and guests","Families and event organisers"],["Airport pickup and drop-off","Hourly and full-day chauffeur service","Meeting and event transport","Hotel transfers","Corporate transport plans","Vehicle selection and booking"]],
 ["airport-transfers","Airport Transfers","chauffeur-transport","Coordinate a reliable airport pickup or drop-off with flight, passenger and luggage requirements captured in advance.",["Arriving founders and families","Business visitors","Corporate guests"],["Flight-detail coordination","Meet-and-greet planning","Vehicle matching","Hotel and office transfers","Return journey booking"]],
 ["corporate-transportation","Corporate Transportation","chauffeur-transport","Plan recurring or event-based transportation for employees, executives and business guests.",["Companies","Conference and event teams","Executive offices"],["Route and schedule planning","Executive chauffeur bookings","Guest transport","Multi-vehicle coordination","Account and itinerary management"]],
];

export const categoryMeta:Record<CategoryKey,{name:string;title:string;description:string}> = {
 "business-setup":{name:"Business Setup",title:"Start your UAE business with the right structure.",description:"We compare the routes around how you plan to trade, hire and grow, then coordinate licensing and the connected setup steps."},
 visas:{name:"Residency & Visas",title:"A clearer route to UAE residency.",description:"From founders and employees to eligible family members, we coordinate the documents, appointments and status steps around your situation."},
 accounting:{name:"Bookkeeping & Accounting",title:"Know where your business stands every month.",description:"We keep your books, reconciliations and reports organised so decisions and compliance work begin with reliable numbers."},
 "tax-accounting":{name:"Tax, Payroll & Audit",title:"Stay prepared for every reporting obligation.",description:"We help organise VAT, Corporate Tax, payroll, WPS and audit readiness with a clear view of what is due and what comes next."},
 "corporate-legal":{name:"Corporate & Legal Support",title:"Handle important matters with clarity and care.",description:"We coordinate documents, estates, succession and compliance, involving appropriately qualified professionals whenever regulated work is required."},
 "corporate-services":{name:"Corporate Services",title:"Keep your business moving after setup.",description:"From banking readiness and government administration to trademarks, payments and relocation, we help connect the operational details."},
 "property-valuation":{name:"Property Valuation",title:"Get the right valuation for the purpose.",description:"We coordinate approved residential and commercial valuation support for finance, investment, reporting and eligible residency requirements."},
 logistics:{name:"Freight & Logistics",title:"Move commercial cargo with fewer loose ends.",description:"We coordinate air, sea and road freight across documentation, customs, cargo handling, delivery and warehousing requirements."},
 "chauffeur-transport":{name:"Chauffeur & Transportation",title:"Professional transport, arranged around your schedule.",description:"We organise airport transfers, executive chauffeur services and corporate transport for individuals, guests and teams."},
};

export const services:Service[] = seeds.map(([slug,name,category,heroDescription,audiences,assistance,regulated,regulatedFallback])=>({
 slug,name,navLabel:name,category,heroTitle:name,heroDescription,
 intro:`Common situations for ${name} include: ${audiences.slice(0,2).join("; ")}. Key areas of support can include: ${assistance.slice(0,3).join("; ")}. The exact route and scope are confirmed after reviewing the case.`,
 audiences,assistance,process:commonProcess,
 considerations:["Requirements vary by authority, jurisdiction, activity and applicant circumstances.","Documents should be checked for validity, naming consistency, translation and attestation needs before submission.","Fees and timeframes are confirmed only after the case and current requirements are reviewed.","Related licence, visa, tax, banking or legal steps should be identified early to avoid duplicated work."],
 faq:commonFaq(name,assistance),cta:`Discuss ${name}`,regulated:regulatedFallback??regulated
}));

export const getService=(slug:string)=>services.find(s=>s.slug===slug);
export const byCategory=(category:CategoryKey)=>services.filter(s=>s.category===category);
